"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
from celery.schedules import crontab
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG',cast=bool)

ALLOWED_HOSTS = ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'rest_framework',
    'core',
    'users',
    'auth_app',
    'corsheaders',
    'channels',
    'posts',
    'chat',
    'django_celery_beat',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CriticalErrorAlertMiddleware'
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/"temps"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.User'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/django-static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'config.throttles.RoleBasedRateThrottle',
        'config.throttles.RequestOTPThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
        'user': '100/minute',
        'admin': '1000/minute',
        'otp_request': '1/minute',
    },

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'auth_app.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('ACCESS_TOKEN_MINUTES', cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('REFRESH_TOKEN_DAYS', cast=int)),
    'BLACKLIST_AFTER_ROTATION': True,
    
}

JWT_COOKIE_NAME =config("JWT_COOKIE_NAME")
JWT_COOKIE_REFRESH_NAME =config("JWT_COOKIE_REFRESH_NAME")
JWT_COOKIE_SECURE = config("JWT_COOKIE_SECURE",cast=bool)
JWT_COOKIE_HTTPONLY = config("JWT_COOKIE_HTTPONLY",cast=bool)
MAX_ACTIVE_TOKENS = config('MAX_ACTIVE_TOKENS', cast=int)


EMAIL_BACKEND =config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = int(config("EMAIL_PORT"))
EMAIL_USE_TLS = config("EMAIL_USE_TLS",cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
LOGGING_EMAIL_RECIPIENTS = config("LOGGING_EMAIL_RECIPIENTS")


CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]
)
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)


SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', default=True, cast=bool)
SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', default=True, cast=bool)
# اگر از HTTPS استفاده می‌کنی:
# SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)



TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN")
BALE_BOT_TOKEN = config("BALE_BOT_TOKEN")

CELERY_BROKER_URL =config("CELERY_BROKER_URL") 
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")  

DAILY_REPORT_HOUR = config('CELERY_TASK_DAILY_REPORT_HOUR',cast=int)
DAILY_REPORT_MINUTE = config('CELERY_TASK_DAILY_REPORT_MINUTE',cast=int)
HEALTH_CHECK_INTERVAL = config('CELERY_TASK_HEALTH_CHECK_INTERVAL',cast=float)

CELERY_BEAT_SCHEDULE = {
    'daily-log-report': {
        'task': 'core.tasks.daily_log_report',
        'schedule': crontab(hour=DAILY_REPORT_HOUR, minute=DAILY_REPORT_MINUTE),
    },
    'health-check': {
    'task': 'core.tasks.health_check',
    'schedule': HEALTH_CHECK_INTERVAL,
    },
}
CELERY_TIMEZONE = 'Asia/Tehran'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


AI_SERVICE_URL = config('AI_SERVICE_URL')

USER_SPACE_STORAGE = int(config('USER_SPACE_STORAGE'))

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
    'context': {
        '()': 'core.logging_filters.ContextFilter',
        },
    'hide_telegram_requests': {
        '()': 'core.logging_filters.TelegramRequestFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '[{asctime}] [{levelname}] {name}::{module}.{funcName}::{message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] [{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file_all': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'all.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 7,
            'formatter': 'verbose',
            'filters': ['context','hide_telegram_requests'],
        },
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 7,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['hide_telegram_requests'],
            
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file_all', 'file_error', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'core': {
            'handlers': ['file_all', 'file_error','console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.task': {
        'handlers': ['file_all', 'file_error', 'console'],
        'level': 'INFO',
        'propagate': False,
        },
        'auth_app': {
            'handlers': ['file_all', 'file_error','console'],
            'level': 'INFO',
            'propagate': False,
        },
        'posts': {
            'handlers': ['file_all', 'file_error','console'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['file_all', 'file_error','console'],
            'level': 'INFO',
            'propagate': False,
        },
        'chat': {
            'handlers': ['file_all', 'file_error','console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['file_all','console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['file_all','console'],
            'level': 'INFO',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['file_all', 'console'],
            'level': 'INFO',
            'propagate': False,
            'filters': ['hide_telegram_requests'],
        },
        'urllib3.connectionpool': {
            'handlers': ['file_all', 'console'],
            'level': 'INFO',
            'propagate': False,
            'filters': ['hide_telegram_requests'],
        },
        'requests': {
            'handlers': ['file_all', 'console'],
            'level': 'INFO',
            'propagate': False,
            'filters': ['hide_telegram_requests'],
        },
    },
}

