# Generated by Django 5.2.11 on 2026-02-14 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: جامعه بزرگان', max_length=100)),
                ('username', models.CharField(help_text='مثلاً: @boz_community', max_length=100)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('platform_channel_id', models.CharField(blank=True, help_text='شناسه کانال در پلتفرم مربوطه (مثلاً chat_id)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
